WEBSITES:
  CODTRACKER:
    xpath_dir:
      player_name_xpath: '//span[@class="trn-ign__username"]'
      match_list_page: '//div[@class="trn-gamereport-list trn-gamereport-list--compact"]/div[@class="trn-gamereport-list__group"]'
      place: '//div[@class="match-row__placement"]'
      game_mode: '//div[@class="match-row__details"]/div[@class="match-row__value"]'
      loby_kd: '//div[@class="match-row__kd"]/div[@class="match-row__value"]'
      kills: '//div[@class="match-row__stats-stat"]/div[@class="match-row__value"]'
      button: '//div[@class="trn-gamereport-list__group"]/span[@class="trn-gamereport-list__group-more"]/button[@class="trn-button"]'
      a_tag: '//a[@class="match-row__link"]'
      b_stats: '//div[@class="player"]/div[@class="player-header"]'
      player: '//div[@class="player-details"]/div[@class="left"]/div[@class="stat"]/div'
      enemy_name: '//div[@class="player-header"]/div[@class="name"]/a'
