WEBSITES:
  CODTRACKER:
    xpath_dir:
      player_name_xpath: '//span[@class="trn-ign__username"]'
      match_list_page: '//div[@class="trn-gamereport-list trn-gamereport-list--compact"]/div[@class="trn-gamereport-list__group"]'
      place: '//div[@class="match-row__placement"]'
      game_mode: '//div[@class="match-row__details"]/div[@class="match-row__value"]'
      loby_kd: '//div[@class="match-row__kd"]/div[@class="match-row__value"]'
      kills: '//div[@class="match-row__stats-stat"]/div[@class="match-row__value"]'
